from E_mart.views import *
from django.urls import path

urlpatterns = [
    path('',HomeView.as_view(), name='home'),
    path('login/',LoginView.as_view(), name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),
    path('signup/',SignupView.as_view(), name='signup'),
    path('send-otp/',OtpSendView.as_view(), name='send_otp'),
    path('verify-otp/',VerifyOtpView.as_view(), name='verify_otp'),
    
    path('admin/',AdminHomeView.as_view(), name='admin'),
    path('admin/login/',AdminLoginView.as_view(), name="admin_login"),
    path('admin/users/', AdminUserManagementView.as_view(), name='admin_user_management'),
    path('admin/api/users/toggle-status/', AdminUserToggleActiveView.as_view(), name='admin_user_toggle'),
    path('admin/api/users/create/', AdminUserCreateAPIView.as_view(), name='admin_user_create_api'),
    path('admin/api/users/<int:user_id>/update/', AdminUserUpdateAPIView.as_view(), name='admin_user_update_api'),
    path('admin/api/users/<int:user_id>/', AdminUserDetailAPIView.as_view(), name='admin_user_detail_api'),
    
    path('admin/posters/', AdminPosterListView.as_view(), name='admin_poster_list'),
    path('admin/api/posters/create/', AdminPosterCreateView.as_view(), name='admin_poster_create'),
    path('admin/api/posters/<int:poster_id>/', AdminPosterDetailView.as_view(), name='admin_poster_detail'),
    path('admin/api/posters/toggle-status/', AdminPosterToggleActiveView.as_view(), name='admin_poster_toggle'),
    path('admin/api/posters/<int:poster_id>/update/', AdminPosterUpdateView.as_view(), name='admin_poster_update'),

    path('admin/categories/', AdminCategoryManagementView.as_view(), name='admin_category_management'),
    path('admin/api/categories/create/', AdminCategoryCreateAPIView.as_view(), name='admin_category_create_api'),
    path('admin/api/categories/<int:category_id>/update/', AdminCategoryUpdateAPIView.as_view(), name='admin_category_update_api'),
    path('admin/api/categories/toggle-status/', AdminCategoryToggleActiveView.as_view(), name='admin_category_toggle'),
    path('admin/api/categories/<int:category_id>/', AdminCategoryDetailAPIView.as_view(), name='admin_category_detail_api'),


    path('admin/products/', AdminProductListView.as_view(), name='admin_product_list'),
    path('admin/api/products/create/', AdminProductCreateView.as_view(), name='admin_product_create'),
    path('admin/api/products/<int:product_id>/', AdminProductDetailView.as_view(), name='admin_product_detail'),
    path('admin/api/products/<int:product_id>/update/', AdminProductUpdateView.as_view(), name='admin_product_update'),
    path('admin/api/products/toggle-status/', AdminProductToggleActiveView.as_view(), name='admin_product_toggle'),

    path('admin/orders/', AdminOrderListView.as_view(), name='admin_order_list'),
    path('admin/orders/filtered/', AdminFilteredOrdersView.as_view(), name='admin_order_filtered'),
    path('admin/api/orders/create/', AdminOrderCreateView.as_view(), name='admin_order_create'),
    path('admin/api/orders/<int:order_id>/', AdminOrderDetailView.as_view(), name='admin_order_detail'),
    path('admin/api/orders/<int:order_id>/update/', AdminOrderUpdateView.as_view(), name='admin_order_update'),
    path('admin/api/orders/<int:order_id>/delete/', AdminOrderDeleteView.as_view(), name='admin_order_delete'),
    path('admin/api/orders/toggle-status/', AdminOrderToggleActiveView.as_view(), name='admin_order_toggle'),
    path('admin/unassigned/orders/', AdminUnassignedOrdersView.as_view(), name='admin_unassigned_orders'),
    path('admin/unassigned/pickups/', AdminUnassignedPickupsView.as_view(), name='admin_unassigned_pickups'),

    path('admin/deliveries/',  AdminDeliveryOrPickupListView.as_view(), name='admin_delivery_list'),
    path('admin/api/deliveries/create/',  AdminDeliveryOrPickupCreateView.as_view(), name='admin_api_delivery_create'),
    path('admin/api/deliveries/<int:delivery_id>/',  AdminDeliveryOrPickupDetailView.as_view(), name='admin_api_delivery_detail'),
    path('admin/api/deliveries/<int:delivery_id>/update/',  AdminDeliveryOrPickupUpdateView.as_view(), name='admin_api_delivery_update'),
    path('admin/api/deliveries/toggle-active/',  AdminDeliveryOrPickupToggleActiveView.as_view(), name='admin_api_delivery_toggle'),

    path('admin/exchange-requests/', AdminExchangeListView.as_view(), name='admin_exchange_list'),
    path('admin/exchange-requests/create/', AdminExchangeCreateView.as_view(), name='admin_exchange_create'),
    path('admin/exchange-requests/<int:exchange_id>/detail/', AdminExchangeDetailView.as_view(), name='admin_exchange_detail'),
    path('admin/exchange-requests/update/<int:exchange_id>/', AdminExchangeUpdateView.as_view(), name='admin_exchange_update'),
    path('admin/exchange-requests/toggle-active/', AdminExchangeToggleActiveView.as_view(), name='admin_exchange_toggle_active'),
    path('admin/exchange/get-order-items/<int:order_id>/', GetOrderItemsView.as_view(), name='get_order_items'),
    path('api/admin/notifications/', AdminNotificationsView.as_view(), name='admin-notifications-api'),

    #enduser

    path('api/categories/',ApiGetAllCategory, name='api_get_categories'),
    path('products/<int:category_id>/',CategoryProductList.as_view(), name='category_products'),  
    path('api/products/search/', ProductSearchView.as_view(), name='product-search'),
    path('user/profile/', UserProfileView.as_view(), name='user_profile'),
    path('profile/update/', UserProfileUpdateView.as_view(), name='profile-update'),
    path('product/<int:product_id>/',ProductDetailsView.as_view(), name='product_details'), 
    path('product-order/summary/',ProductOrderSummary.as_view(), name='product_order_summary'),
    path('cart-product-order/summary/',ProductsOrderSummaryByCart.as_view(), name='cart_product_order_summary'),
    path('user/cart/',UserCartDetailsView.as_view(), name='user_cart'),
    path('order/create/',OrderCreateView.as_view(),name='order_create'),
    path('order/delete/',OrderDeleteView.as_view(),name='order_delete'),
    path('delete/order/<int:order_id>/',OrderPermanentDeleteView.as_view(),name='order_permanent_delete'), 
    path('orders/',OrderListView.as_view(),name='order_list'),
    path('order/<int:order_id>/',OrderDetailsView.as_view(),name='order_details'),
    path('user/cart/create-data/',UserCartCreateDataView.as_view(), name='user_cart_create_data'),
    path('api/cart/remove-item/<int:cart_id>/',ApiRemoveCartItem.as_view(), name='cart_remove_item'),
    path('api/product-quantity/update/<int:item_id>/', CartItemUpdateView.as_view(), name="cartitem-update"),
    path('api/payment/create/', ApiPaymentCreateView.as_view(), name="payment_create_api"),
    path('wishlist/', WishlistListView.as_view(), name="user_wishlist"),
    path('review/create/', ReviewCreateView.as_view(), name='review_create'),
    path('wishlist/delete-item/<int:wishlist_id>/', WishlistItemDeleteView.as_view(), name="wishlist_item_delete"),
    path('create/payment/<int:order_id>/',PaymentCreateView.as_view(), name='payment_create'),
    path('wishlist/toggle/<int:product_id>/',ToggleWishlistCreateDelete.as_view(), name='wishlist_toggler'),
    path('wishlist/check/<int:product_id>/', CheckWishlistStatus.as_view(), name='check_wishlist'),
    path('exchange-return/create/<int:order_id>/', ExchangeReturnCreateView.as_view(), name='exchange_return_create'),
    path('exchanges-or-returns/', ExchangeReturnListView.as_view(), name='exchange_return_list'),
    path('exchanges-or-returns/<int:pk>/', ExchangeReturnDetailsView.as_view(), name='exchange_return_details'),

    #delivery worker
    path('delivery-worker/',DeliveryWorkerHomeView.as_view(), name='delivery_worker_home'),
    path('delivery-worker/profile/',DeliveryWorkerProfileView.as_view(), name='delivery_worker_profile'),
    path('deliveries/',DeliveriesListView.as_view(), name='deliveries_list'),
    path('pickups/',PickUpsListView.as_view(), name='pickups_list'),
    path("delivery-worker/delivery/order-details/<int:order_id>/", DeliveryOrderDetails.as_view(), name="worker_delivery_order_details"),
    path("delivery-worker/pickup/order-details/<int:order_id>/", PickupOrderDetails.as_view(), name="worker_pickup_order_details"),
    path('api/delivery/<int:delivery_id>/status/update/', DeliveryStatusUpdateView.as_view(), name='delivery_status_update'),
    path('api/pickup/<int:pickup_id>/status/update/', PickupStatusUpdateView.as_view(), name='pickup_status_update'),
    path('admin/workers/', AdminWorkerManagementView.as_view(), name='admin_worker_management'),
    path('admin/api/workers/toggle-status/', AdminWorkerToggleActiveView.as_view(), name='admin_worker_toggle'),
    path('admin/api/workers/create/', AdminWorkerCreateAPIView.as_view(), name='admin_worker_create_api'),
    path('admin/api/workers/<int:worker_id>/update/', AdminWorkerUpdateAPIView.as_view(), name='admin_worker_update_api'),
    path('admin/api/workers/<int:worker_id>/', AdminWorkerDetailAPIView.as_view(), name='admin_worker_detail_api'),
    path('api/delivery-worker/notifications/',DeliveryOrPickupNotifications.as_view(),name='api_delivery_pickup_notification'),


   # Page render route
    path('contact/', ContactPageView.as_view(), name='contact_page'),
    
    # API endpoints for dynamic operations
    path('contact/submit/', SubmitContactQuery.as_view(), name='submit_contact'),
    path('contact/queries/', GetContactQueries.as_view(), name='get_queries'),
    path('help/problems/', GetHelpProblems.as_view(), name='get_help_problems'),
    path('help/problem/<int:problem_id>/', GetHelpProblemDetail.as_view(), name='problem_detail'),
    path('help/problem/submit/', SubmitHelpProblem.as_view(), name='submit_problem'),
    path('help/problem/update-status/', UpdateHelpProblemStatus.as_view(), name='update_problem_status'),
    path('help/faqs/', GetFAQs.as_view(), name='get_faqs'),
    path('help/dashboard-stats/', GetDashboardStats.as_view(), name='dashboard_stats'),
    path('chat/send/', SendChatMessage.as_view(), name='send_chat'),
]
