from .auth_view import *
from .home_view import *
from .user_view import *
from .poster_view import *
from .category_view import *
from .product_view import *
from .wishlist_view import *
from .product_details_view import *
from .cart_view import *
from .order_view import *