from .auth_view import *
from .home_view import *
from .user_view import *
from .poster_view import *
from .category_view import *
from .product_view import *
from .wishlist_view import *
from .cart_view import *
from .order_view import *
from .worker_view import *
from .Review_view import *
from .payment_view import *
from .delivery_or_pickup_view import *
from .exchnage_or_return_view import *